language: c
os:
  - linux
before_install:
  - git clone https://github.com/jedisct1/libsodium
  - cd libsodium
  - ./autogen.sh
  - ./configure
  - make install
compiler:
  - clang
  - gcc
script:
 - ./configure
 - make