language: c
os:
  - linux
before_install:
  - git clone https://github.com/jedisct1/libsodium
  - cd libsodium
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
  - ./autogen.sh
  - git clone https://github.com/tlinden/p5mods tests/lib
compiler:
  - clang
  - gcc
script:
 - ./configure
 - find tests/lib -ls
 - make
 - make check
 - make test

