language: c
os:
  - linux
before_install:
  - git clone https://github.com/jedisct1/libsodium
  - cd libsodium
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - ./autogen.sh
  - cpanm Test::More IPC::Open3 Config::General Tie::IxHash
compiler:
  - clang
  - gcc
script:
 - ./configure
 - make
 - make check
 - make test
