sudo: false
language: c
os:
  - linux

addons:
  apt:
    packages:
      - python-pip
      - texinfo

compiler:
  - clang
  - gcc
 
before_install:
  # runtime dependency
  - git clone https://github.com/jedisct1/libsodium
  - cd libsodium
  - ./autogen.sh
  - ./configure --prefix=$HOME/usr
  - make
  - make install
  - cd ..
  #
  # for debugging - just in case, uncomment this and the next if needed
  #- wget http://valgrind.org/downloads/valgrind-3.10.1.tar.bz2
  #- tar xvjf valgrind-3.10.1.tar.bz2
  #- cd valgrind-3.10.1
  #- ./configure --prefix=/usr
  #- make
  #- sudo make install
  #- cd ..
  #
  # valgrind runtime dependency
  #- sudo apt-get update
  #- sudo apt-get install libc6-dbg
  #
  # python bindings runtime dependencies
  #- git clone https://github.com/atgreen/libffi
  #- cd libffi
  #- ./autogen.sh
  #- ./configure --prefix=/usr
  #- make
  #- sudo make install
  #- cd ..
  #- sudo pip install cffi
  #
  # finally prepare autoconf stuff
  - ./autogen.sh

script:
 #- ./configure --enable-python-binding
 - LD_LIBRARY_PATH=$HOME/usr/lib ./configure --with-libsodium=$HOME/usr
 - make
 - make check
 - make test
 #
 # upload last fuzzy testfiles in case one of them failed
 - cd tests
 - cat testfuzzP.pub | openssl base64 | curl -F 'sprunge=<-' http://sprunge.us
 - cat testfuzzS.sec | openssl base64 | curl -F 'sprunge=<-' http://sprunge.us
