language: c
os:
  - linux
before_install:
  - git clone https://github.com/jedisct1/libsodium
  - cd libsodium
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd ..
  - ./autogen.sh
  - perl -MIPC::Open3 -e0
  - perl -MTest::More
compiler:
  - clang
  - gcc
script:
 - ./configure
 - make
