language: c
os:
  - linux
before_install:
  - git clone git@github.com:jedisct1/libsodium.git
  - cd libsodium
  - ./autogen.sh
  - ./configure
  - make
  - cd ..
  - ./autogen.sh
compiler:
  - clang
  - gcc
script:
 - ./configure --with-libsodium-lib-dir libsodium/src/libsodium/.libs --with-libsodium-include-dir libsodium/src/libsodium/include
 - make